version: "3.7"
services:
  snow:
    build: ./
    container_name: snow
    ports:
    - 8080:8080
    volumes:
    - "./- volume:/tmp"
    networks:
      base_net:
        ipv4_address: 11.11.11.11
networks:
  base_net:
    external:
      name: base