server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://60.205.195.79:3306/snow?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwer1234

  redis:
    host: 60.205.195.79
    port: 6379
    database: 0
    password: qwer1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 300
