server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://212.64.19.103:3306/bookstack?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: c2hhb2Zlbmd4aWE=

  redis:
    host: 212.64.19.103
    port: 6379
    database: 0
    password: qwer1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 300
