server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://60.205.195.79:3306/snow?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: c2hhb2Zlbmd4aWE=
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 60.205.195.79
    port: 6379
    database: 0
    password: c2hhb2Zlbmd4aWE=
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 300
